language: python
python:
  - 3.6
services:
    - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - export TEST_DATABASEURI="dbname='sendit_test' user='smokes' password='smokey' host='localhost'"
  - export DATABASEURI="dbname='sendit_test' user='smokes' password='smokey' host='localhost'"
  - export JWT_SECRET_KEY="shh_shhuutt_uup"
before_script:
    - psql -c 'create database sendit_test;' -U postgres
    - psql -c "create user smokes with password 'smokey';" -U postgres
script:
  - coverage run -m unittest discover && coverage report

after_success:
  - coveralls
